### ISSUE TITLE
Use N4ITK to correct the data

### ISSUE THREAD

**Issue by ahuczp** [lelechen63/MRI-tumor-segmentation-Brats#1]
why do we need to "Use N4ITK to correct the data"? many thanks.

**Comment by lelechen63** [comment]
We employ N4ITK bias correction12 for all MRI sequences. This algorithm removes the intensity gradient of each scan.

**Comment by ahuczp** [comment]
Are you a Chinese? I am new to deep  learning and segmentation.  Do you  use Wechat(微信)？My wechat is ahuczp. I have some questions to ask you .I hope you can become my Wechat friend。
