### ISSUE TITLE
请问keras版本会影响训练结果吗？

### ISSUE THREAD

**Issue by muween** [lelechen63/MRI-tumor-segmentation-Brats#2]
我对keras的tensorflow进行了升级，然后修改了以下部分

```
from tensorflow.contrib.keras.python.keras.backend import ---->
from keras.backend import 
```
再次训练，训练集效果正常，但测试集dice非常低。是因为版本的问题吗，别的地方我都没动。

**Comment by lelechen63** [comment]
I think different keras version is ok. We did use some tricks when we do the project like equally choose labeled cubes and unlabeled cubes to avoid over-fitting problem. You can find those strategies in the paper.

**Comment by muween** [comment]
> I think different keras version is ok. We did use some tricks when we do the project like equally choose labeled cubes and unlabeled cubes to avoid over-fitting problem. You can find those strategies in the paper.

ok, thank you!

**Comment by lelechen63** [comment]
> > I think different keras version is ok. We did use some tricks when we do the project like equally choose labeled cubes and unlabeled cubes to avoid over-fitting problem. You can find those strategies in the paper.
> 
> ok, thank you!

**Comment by hjyai94** [comment]
> 我对keras的tensorflow进行了升级，然后修改了以下部分
> 
> ```
> from tensorflow.contrib.keras.python.keras.backend import ---->
> from keras.backend import 
> ```
> 再次训练，训练集效果正常，但测试集dice非常低。是因为版本的问题吗，别的地方我都没动。

请问一下您训练得到的模型测试时的dice是多少？我的结果是这个样子的：
mean dice whole:
[0.77416498 0.05540441]
mean dice core:
[0.99640544 0.00410985]
mean dice enhance:
[0.99734054 0.00442083]

**Comment by muween** [comment]
> > 我对keras的tensorflow进行了升级，然后修改了以下部分
> > ```
> > from tensorflow.contrib.keras.python.keras.backend import ---->
> > from keras.backend import 
> > ```
> > 再次训练，训练集效果正常，但测试集dice非常低。是因为版本的问题吗，别的地方我都没动。
> 
> 请问一下您训练得到的模型测试时的dice是多少？我的结果是这个样子的：
> mean dice whole:
> [0.77416498 0.05540441]
> mean dice core:
> [0.99640544 0.00410985]
> mean dice enhance:
> [0.99734054 0.00442083]

没错，和你这个差不多。最后因为时间问题，我就没继续找原因。

**Comment by lelechen63** [comment]
> > 我对keras的tensorflow进行了升级，然后修改了以下部分
> > ```
> > from tensorflow.contrib.keras.python.keras.backend import ---->
> > from keras.backend import 
> > ```
> > 再次训练，训练集效果正常，但测试集dice非常低。是因为版本的问题吗，别的地方我都没动。
> 
> 请问一下您训练得到的模型测试时的dice是多少？我的结果是这个样子的：
> mean dice whole:
> [0.77416498 0.05540441]
> mean dice core:
> [0.99640544 0.00410985]
> mean dice enhance:
> [0.99734054 0.00442083]
你好，我想了想可能版本是有影响，因为当初这个结果要按照计算的受众面积来计算， 现在的更新我还得看一下这些normalization或者别的参数会不会影响到，另外，你是按照我的方法划分数据集的吗

**Comment by hjyai94** [comment]
> > > 我对keras的tensorflow进行了升级，然后修改了以下部分
> > > ```
> > > from tensorflow.contrib.keras.python.keras.backend import ---->
> > > from keras.backend import 
> > > ```
> > > 再次训练，训练集效果正常，但测试集dice非常低。是因为版本的问题吗，别的地方我都没动。
> > 
> > 
> > 请问一下您训练得到的模型测试时的dice是多少？我的结果是这个样子的：
> > mean dice whole:
> > [0.77416498 0.05540441]
> > mean dice core:
> > [0.99640544 0.00410985]
> > mean dice enhance:
> > [0.99734054 0.00442083]
> > 你好，我想了想可能版本是有影响，因为当初这个结果要按照计算的受众面积来计算， 现在的更新我还得看一下这些normalization或者别的参数会不会影响到，另外，你是按照我的方法划分数据集的吗

我是按照您的方法划分的数据集，另外我用的是tensorflow1.5， keras2.2.4。
