### ISSUE TITLE
Visualze Prediction

### ISSUE THREAD

**Issue by ikramabdel** [lelechen63/MRI-tumor-segmentation-Brats#6]
I have trained the dense 24 with Batch size 2 and Epoch 5 and the prediction result is very bad. 
I think what i am doing ( reshaping the prediction array to (240,240,155)) is wrong , please if anyone can help me correctly visualize the prediction results i would appreciate it . 

Thank you

**Comment by lelechen63** [comment]
Hi, you should permute the dimension rather than reshap
